# Generated by Django 5.0.6 on 2024-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(),
        ),
    ]
