# Generated by Django 5.0.6 on 2024-05-25 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0002_remove_appointment_date_remove_appointment_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
