# Generated by Django 5.0.6 on 2024-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0005_remove_quote_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("Teeth Whitening", "Teeth Whitening"),
                    ("Teeth Cleaning", "Teeth Cleaning"),
                    ("Quality Brackets", "Quality Brackets"),
                    ("Modern Anesthetic", "Modern Anesthetic"),
                ],
                default="Teeth Whitening",
                max_length=50,
            ),
        ),
    ]
