# Generated by Django 5.0.6 on 2024-05-27 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0007_appointment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user",
        ),
    ]
