# Generated by Django 5.0.6 on 2024-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0009_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
