# Generated by Django 5.0.6 on 2024-05-30 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0012_appointment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    # Other operations...
    migrations.AlterField(
        model_name='appointment',
        name='user',
        field=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True),
    ),
]

