# Generated by Django 5.0.6 on 2024-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0014_alter_appointment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="appointment_images/"
            ),
        ),
    ]
