# Generated by Django 5.0.6 on 2024-05-30 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0015_appointment_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="image",
        ),
    ]
