# Generated by Django 5.0.6 on 2024-06-02 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0018_remove_product_price_product_stripe_product_id_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
