# Generated by Django 5.0.6 on 2024-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0019_delete_price_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user",
        ),
        migrations.AddField(
            model_name="quote",
            name="testimonial",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(),
        ),
    ]
