# Generated by Django 5.0.6 on 2024-06-02 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomanapp", "0020_remove_appointment_user_quote_testimonial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("Teeth Whitening", "Teeth Whitening"),
                    ("Teeth Cleaning", "Teeth Cleaning"),
                    ("Quality Brackets", "Quality Brackets"),
                    ("Modern Anesthetic", "Modern Anesthetic"),
                ],
                default="Teeth Whitening",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
